# --- Change what appears in the banner --- #
title: Example website
description: To demonstrate the template and ideas for content.

# --- Change language of site --- #
lang: en

# --- List of links in the navigation bar --- #
# --- Change only the black entry if you change the name of your .md files!! --- #
github:
  page1: index.html
  page2: page2.html
  page3: page3.html
  page4: page4.html
  page5: page5.html
  page6: maps.html
  page7: js-basics.html
  page8: js-random.html
  page9: wikisearch.html
  page10: games.html
  blog: blog.html
  
